# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_test_data.ipynb.

# %% auto 0
__all__ = ['test_spectra', 'select_test_file']

# %% ../nbs/10_test_data.ipynb 8
test_spectra = [  
  {"spectra_fn":"/mnt/s/2021-0717-HAB-Spec-Tampa-Bay-PIE/2021-0717-HAB-pie/164443/hab_spectra/2021-0717-164700-525866-spec.json",
         "Note":"0. No embedded GPS data. Gulf of Mexico west of Clearwater."
  },
  
  {"spectra_fn":"/mnt/s/2021-0717-HAB-Spec-Tampa-Bay-PIE/2021-0717-HAB-pie/165347/hab_spectra/2021-0717-165910-141598-spec.json",
         "Note":"1. Old Tampa Bay.  No embedded GPS data. Very high 700nm peak"
  },
  
  {"spectra_fn":"/mnt/s/2021-1208-HAB-Lake-Parker/2021-1208-HAB-Lake-Parker/190829/hab_spectra/2021-1208-190953-177078-spec.json",
         "Note":"2. Lake Parker, Water.  No embedded GPS data." 
  },
  
  {"spectra_fn":"/mnt/s/2021-1208-HAB-Lake-Parker/2021-1208-HAB-Lake-Parker/175549/hab_spectra/2021-1208-175627-867603-spec.json",
         "Note":"3. Lake Parker, Sky. No embedded GPS data."
  },  
  {"spectra_fn":"../sample_data/2023-0718/034901/hab_spectra/2023-0718-034909-929994-spec.json",
          "Note":"4. Has embedded GPS data."
  },
  {
    "spectra_fn":"/mnt/s/2021-1208-HAB-Lake-Parker/2021-1208-HAB-Lake-Parker/191543/hab_spectra/2021-1208-191607-388708-spec.json",
          "Note":"5. Lake Parker Sky Spectra with teflon difuser. No embedded GPS data. "
  }
  
]

# %% ../nbs/10_test_data.ipynb 9
def select_test_file( 
  idx                 # Index number to select test file and note.
) ->tuple:            # A tuple with (test_file_name, Note)
  '''
  '''
  spectra_fn   = test_spectra[idx]['spectra_fn']
  spectra_note = test_spectra[idx]['Note']
  return spectra_fn, spectra_note
