# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/30_wavelength_cal.ipynb.

# %% auto 0
__all__ = ['Fraunhofer_lines', 'HG_lines', 'gen_reference_lines']

# %% ../nbs/30_wavelength_cal.ipynb 5
# see: [Solar Spectral Irradiance](https://en.wikipedia.org/wiki/Fraunhofer_lines#/media/File:Solar_spectral_irradiance.svg)
Fraunhofer_lines = {
                'y' :[ 'O2', 898.765  ],
                'Z' :[ 'O2', 822.696  ],
                'A' :[ 'O2', 759.370  ],
                'B' :[ 'O2', 686.719  ], 
                'C' :[ 'Ha', 656.281  ],
                'a' :[ 'O2', 627.661  ],
                'D1':[ 'Na', 589.592  ],
                'D2':[ 'Na', 588.995  ],
                'D3':[ 'He', 587.5618 ],
              'e-hg':[ 'Hg', 546.073  ],
                'E2':[ 'Fe', 527.039  ],
                'b1':[ 'Mg', 518.362  ],
                'b2':[ 'Mg', 517.270  ],
                'b3':[ 'Mg', 516.891  ],
                'b4':[ 'Mg', 516.733  ],
                'c' :[ 'Fe', 495.761  ],                                                            
                'F' :[ 'Hb', 486.134  ],
                'd' :[ 'Fe', 466.814  ],
              'e-Fe':[ 'Fe', 438.355  ],
                'G' :[ 'Fe', 430.790  ],
                'G2':[ 'Ca', 430.774  ],
                'H' :[ 'Ca', 396.847  ] 
}

# %% ../nbs/30_wavelength_cal.ipynb 14
HG_lines = { 
          'Hg-404' :[ 'Hg', 404.6563 ],
          'Hg-436' :[ 'Hg', 435.8328 ],
          'Hg-543' :[ 'Hg', 543.6    ],
          'Hg-546' :[ 'Hg', 546.0735 ],
          'Hg-576' :[ 'Hg', 576.959  ],
          'Hg-579' :[ 'Hg', 579.065  ],
          'Hg-611' :[ 'Hg', 610.8    ],
          'Hg-615' :[ 'Hg', 614.9475 ],
          'Hg-707' :[ 'Eu', 707.0],
          'Hg-709' :[ 'Eu', 709.0]
}

# %% ../nbs/30_wavelength_cal.ipynb 16
def gen_reference_lines( 
              lines,            # The reference lines.
              y_max = 100.0,      # Max value for y.
              y_min = 0,
             ) -> (list,list):  # Fraun X values, Fraun y values 
  '''
  Generate a series of spectral plot lines for reference.  It scales to the max y value 
  of the provided spectra within `hab_spec_class`.  Sources can be Fraunhofer_lines, or HG_lines, or user 
  developed.
  '''
  fran_x = []; fran_y = []
  y0 = y_min;    y1 = y_max
  for i in lines:
    x = lines[i][1]
    fran_x.append( [ x,x ] )
    fran_y.append( [y0, y1] )
  return fran_x, fran_y
